### ISSUE TITLE
About License

### ISSUE THREAD

**Issue by Yukaii** [chenlijun99/autoanki#13] opened 2023-09-05 13:12 UTC
Hello! Thanks for making this project. I want to check wether it has a open source license, and can I use packages and modified them freely in my projects?

**Comment by chenlijun99** [comment] 2023-09-06 02:25
Hi. Thanks for your interest in this project.
I'm actually undecided between AGPL and MIT. On one hand I would like improvements to the project to be made available to the public, on the other hand probably AGPL is too infectious. I think I really would like to use something like ALGPL, which doesn't exist so far from what I've read  (https://softwareengineering.stackexchange.com/questions/58033/is-there-any-copyleft-gpl-like-license-with-both-the-affero-and-lesser-modific?rq=1). 

Since you're the first developer to bring up this issue, what would be more preferable for you? Do you plan to release the projects in which you'll use the packages in this repository as open source?

**Comment by chenlijun99** [comment] 2023-09-06 03:06
Oh, I just realized that I was already using MIT in all the `package.json` files.

**Comment by Yukaii** [comment] 2023-09-06 04:23
I do prefer MIT more. Currently I'm in the progress of making [anki extension for Raycast](https://github.com/raycast/extensions/compare/main...Yukaii:extensions:feature/anki). 

I copied some code of `@autoanki/anki-connect` into directory, and made some changes including:

- missing API endpoints and typing
- Change axios to cross-fetch that comes from Raycast's SDK dependency

Raycast extensions are in MIT License too, so it would easier to integrate `ank-connect` as MIT License for me.

**Comment by chenlijun99** [comment] 2023-09-06 16:57
I see. Thanks for your feedback. Please feel free to use the @autoanki/anki-connect package, as it is already licensed under MIT.
I've also added a LICENSE file (in which I use the MIT license) to this repository.

I'm closing this issue. Feel free to reopen if you don't think the issue is fully resolved.

**Closed as completed** 2023-09-06 16:58 UTC
